/// Flutter icons MyFlutterApp
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Fontelico, Copyright (C) 2012 by Fontello project
///         Author:    Crowdsourced, for Fontello project
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://fontello.com
///
library;
import 'package:flutter/widgets.dart';

class MudraManagerAvatarIcons {
  MudraManagerAvatarIcons._();

  static const _kFontFam = 'MudraManagerAvatar';
  static const String? _kFontPkg = null;

  static const IconData emoHappy = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_wink = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_unhappy = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_sleep = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_thumbsup = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_devil = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_surprised = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_tongue = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_coffee = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_sunglasses = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_displeased = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_beer = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_grin = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_angry = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_saint = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_cry = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_shoot = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_squint = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_laugh = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_wink2 = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static var iconDataList = [
    MudraManagerAvatarIcons.emoHappy,
    MudraManagerAvatarIcons.emo_wink,
    MudraManagerAvatarIcons.emo_unhappy,
    MudraManagerAvatarIcons.emo_sleep,
    MudraManagerAvatarIcons.emo_thumbsup,
    MudraManagerAvatarIcons.emo_devil,
    MudraManagerAvatarIcons.emo_surprised,
    MudraManagerAvatarIcons.emo_tongue,
    MudraManagerAvatarIcons.emo_coffee,
    MudraManagerAvatarIcons.emo_sunglasses,
    MudraManagerAvatarIcons.emo_displeased,
    MudraManagerAvatarIcons.emo_beer,
    MudraManagerAvatarIcons.emo_grin,
    MudraManagerAvatarIcons.emo_angry,
    MudraManagerAvatarIcons.emo_saint,
    MudraManagerAvatarIcons.emo_cry,
    MudraManagerAvatarIcons.emo_shoot,
    MudraManagerAvatarIcons.emo_squint,
    MudraManagerAvatarIcons.emo_laugh,
    MudraManagerAvatarIcons.emo_wink2,
  ];
}
