import 'package:flutter/material.dart';
import 'package:lucide_icons_flutter/lucide_icons.dart';

class IconHelper {
  static IconData iconFromName(String name) {
    final icon = iconMap[name];
    if (icon == null) {
      debugPrint('⚠️ IconHelper: missing icon "$name"');
      return LucideIcons.circleQuestionMark;
    }
    return icon;
  }

  static final Map<String, Map<String, IconData>> iconGroups = {
    'Financial': {
      'rupee': LucideIcons.indianRupee,
      'rupee_badge': LucideIcons.badgeIndianRupee,
      'rupee_receipt': LucideIcons.receiptIndianRupee,
      'coins': LucideIcons.coins,
      'cash': LucideIcons.banknote,
      'credit_card': LucideIcons.creditCard,
      'wallet': LucideIcons.wallet,
      'pocket_money': LucideIcons.walletMinimal,
      'allowance': LucideIcons.walletCards,
      'savings': LucideIcons.piggyBank,
      'pension': LucideIcons.piggyBank,
      'gratuity': LucideIcons.award,
      'debt': LucideIcons.scale,
      'attach_money': LucideIcons.indianRupee,
      'trending_up': LucideIcons.trendingUp,
      'receipt': LucideIcons.receiptText,
      'receipt_long': LucideIcons.scroll,
      'tax': LucideIcons.receiptIndianRupee,
      'bank': LucideIcons.landmark,
      'insurance': LucideIcons.shieldCheck,
    },
    'Payments & Transfers': {
      'upi': LucideIcons.qrCode,
      'neft': LucideIcons.arrowRightLeft,
      'imps': LucideIcons.zap,
      'cheque': LucideIcons.fileCheck,
      'demand_draft': LucideIcons.fileBadge,
      'deposit': LucideIcons.arrowDownToLine,
      'withdrawal': LucideIcons.arrowUpFromLine,
      'transfer': LucideIcons.repeat2,
      'money_send': LucideIcons.sendHorizontal,
      'money_receive': LucideIcons.cloudDownload,
      'scan_pay': LucideIcons.scanLine,
      'qr_code': LucideIcons.qrCode,
    },
    'Investments': {
      'stocks': LucideIcons.chartCandlestick,
      'mutual_fund': LucideIcons.chartSpline,
      'sip': LucideIcons.calendarPlus,
      'crypto': LucideIcons.bitcoin,
      'gold': LucideIcons.gem,
      'fixed_deposit': LucideIcons.vault,
      'ppf': LucideIcons.lockKeyhole,
      'nps': LucideIcons.shieldCheck,
      'dividend': LucideIcons.sprout,
      'capital_gain': LucideIcons.trendingUp,
      'interest_earned': LucideIcons.percent,
      'rental_income': LucideIcons.building2,
    },
    'Bills & Utilities': {
      'emi': LucideIcons.calendarRange,
      'loan': LucideIcons.handCoins,
      'loan_emi': LucideIcons.handCoins,
      'gst': LucideIcons.receiptIndianRupee,
      'tds': LucideIcons.badgeIndianRupee,
      'cess': LucideIcons.indianRupee,
      'invoice': LucideIcons.receiptText,
      'premium': LucideIcons.shieldPlus,
      'maintenance': LucideIcons.housePlug,
      'property_tax': LucideIcons.landmark,
      'gas_bill': LucideIcons.flame,
      'water_bill': LucideIcons.glassWater,
      'broadband': LucideIcons.router,
      'recharge': LucideIcons.refreshCcw,
      'postpaid': LucideIcons.phoneOutgoing,
      'prepaid': LucideIcons.phoneIncoming,
      'autopay': LucideIcons.timerReset,
      'due_date': LucideIcons.calendarClock,
      'overdue': LucideIcons.calendarX,
      'paid': LucideIcons.circleCheckBig,
      'unpaid': LucideIcons.circleX,
      'split_bill': LucideIcons.split,
      'settlement': LucideIcons.handshake,
      'toll': LucideIcons.milestone,
      'stamp_duty': LucideIcons.stamp,
      'registration': LucideIcons.filePen,
      'bolt': LucideIcons.zap,
      'wifi': LucideIcons.wifi,
      'water': LucideIcons.droplets,
    },
    'Deals & Offers': {
      'cashback': LucideIcons.badgePercent,
      'discount': LucideIcons.ticketPercent,
      'coupon': LucideIcons.ticket,
      'percent': LucideIcons.percent,
      'tag_sale': LucideIcons.badgePercent,
    },
    'Food & Dining': {
      'restaurant': LucideIcons.utensils,
      'fastfood': LucideIcons.sandwich,
      'coffee': LucideIcons.coffee,
      'wine': LucideIcons.wine,
      'cake': LucideIcons.cakeSlice,
      'groceries': LucideIcons.apple,
      'pizza': LucideIcons.pizza,
      'beer': LucideIcons.beer,
      'ice_cream': LucideIcons.iceCreamCone,
      'soup': LucideIcons.soup,
      'salad': LucideIcons.salad,
      'popcorn': LucideIcons.popcorn,
      'cooking': LucideIcons.cookingPot,
      'fish': LucideIcons.fish,
      'beef': LucideIcons.beef,
      'ham': LucideIcons.ham,
      'egg': LucideIcons.egg,
      'wheat': LucideIcons.wheat,
      'cherry': LucideIcons.cherry,
      'grape': LucideIcons.grape,
      'citrus': LucideIcons.citrus,
      'banana': LucideIcons.banana,
      'candy': LucideIcons.candy,
      'croissant': LucideIcons.croissant,
      'cup_soda': LucideIcons.cupSoda,
      'glass_water': LucideIcons.glassWater,
      'martini': LucideIcons.martini,
      'vegan': LucideIcons.vegan,
      'milk': LucideIcons.milkOff,
      'microwave': LucideIcons.microwave,
      'refrigerator': LucideIcons.refrigerator,
      'delivery': LucideIcons.truck,
    },
    'Shopping': {
      'shopping_cart': LucideIcons.shoppingCart,
      'shopping_bag': LucideIcons.shoppingBag,
      'basket': LucideIcons.shoppingBasket,
      'clothing': LucideIcons.shirt,
      'checkroom': LucideIcons.shirt,
      'electronics': LucideIcons.monitor,
      'devices': LucideIcons.smartphone,
      'furniture': LucideIcons.armchair,
      'furniture_new': LucideIcons.sofa,
      'gem': LucideIcons.gem,
      'store': LucideIcons.store,
      'package': LucideIcons.package,
      'box': LucideIcons.box,
      'ribbon': LucideIcons.ribbon,
      'barcode': LucideIcons.barcode,
      'scan': LucideIcons.scanLine,
      'toys': LucideIcons.blocks,
    },
    'Transport': {
      'directions_car': LucideIcons.car,
      'taxi': LucideIcons.carTaxiFront,
      'bus': LucideIcons.bus,
      'directions_bus': LucideIcons.bus,
      'train': LucideIcons.trainFront,
      'subway': LucideIcons.trainFrontTunnel,
      'flight': LucideIcons.plane,
      'bike': LucideIcons.bike,
      'walk': LucideIcons.footprints,
      'parking': LucideIcons.circleParking,
      'boat': LucideIcons.ship,
      'cable_car': LucideIcons.cableCar,
      'tram': LucideIcons.tramFront,
      'rocket': LucideIcons.rocket,
      'navigation': LucideIcons.navigation,
      'route': LucideIcons.route,
      'local_gas_station': LucideIcons.fuel,
      'gas': LucideIcons.fuel,
    },
    'Entertainment': {
      'concert': LucideIcons.mic,
      'podcast': LucideIcons.podcast,
      'streaming': LucideIcons.cast,
      'theatre': LucideIcons.clapperboard,
      'movie': LucideIcons.clapperboard,
      'comedy': LucideIcons.laugh,
      'amusement_park': LucideIcons.ferrisWheel,
      'circus': LucideIcons.tent,
      'board_games': LucideIcons.dice5,
      'karaoke': LucideIcons.micVocal,
      'gaming_console': LucideIcons.monitor,
      'reading': LucideIcons.bookMarked,
      'crafts': LucideIcons.scissors,
      'photography': LucideIcons.aperture,
      'celebration': LucideIcons.partyPopper,
      'park': LucideIcons.trees,
      'tv': LucideIcons.tv,
    },
    'Health & Fitness': {
      'heartbeat': LucideIcons.heartPulse,
      'local_hospital': LucideIcons.hospital,
      'medical': LucideIcons.stethoscope,
      'pharmacy': LucideIcons.pill,
      'fitness': LucideIcons.dumbbell,
      'sports': LucideIcons.trophy,
      'dentist': LucideIcons.smile,
      'eye_care': LucideIcons.eye,
      'blood_test': LucideIcons.testTube,
      'xray': LucideIcons.scan,
      'ambulance': LucideIcons.siren,
      'therapy': LucideIcons.brain,
      'physiotherapy': LucideIcons.accessibility,
      'ayurveda': LucideIcons.leaf,
      'lab_test': LucideIcons.microscope,
      'vaccination': LucideIcons.syringe,
      'health_insurance': LucideIcons.shieldPlus,
      'yoga': LucideIcons.personStanding,
      'haircut': LucideIcons.scissors,
      'skincare': LucideIcons.droplet,
      'perfume': LucideIcons.sprayCan,
      'makeup': LucideIcons.paintbrush,
      'massage': LucideIcons.hand,
      'nails': LucideIcons.paintbrushVertical,
      'tattoo': LucideIcons.penTool,
      'spa': LucideIcons.flower2,
    },
    'Education': {
      'school': LucideIcons.graduationCap,
      'book': LucideIcons.bookOpen,
      'online_course': LucideIcons.monitorPlay,
      'certification': LucideIcons.badgeCheck,
      'workshop': LucideIcons.presentation,
      'language': LucideIcons.languages,
      'coding': LucideIcons.code,
      'research': LucideIcons.searchCode,
      'notebook': LucideIcons.notebookPen,
      'exam': LucideIcons.clipboardCheck,
      'scholarship': LucideIcons.medal,
      'lab': LucideIcons.flaskConical,
      'print': LucideIcons.printer,
    },
    'Home & Family': {
      'home': LucideIcons.house,
      'baby': LucideIcons.baby,
      'kitchen': LucideIcons.cookingPot,
      'plumbing': LucideIcons.pipette,
      'electrician': LucideIcons.plug,
      'painting': LucideIcons.paintRoller,
      'pest_control': LucideIcons.bug,
      'security': LucideIcons.shieldAlert,
      'cctv': LucideIcons.cctv,
      'solar': LucideIcons.sun,
      'ac_service': LucideIcons.airVent,
      'curtains': LucideIcons.blinds,
      'moving': LucideIcons.packageOpen,
      'renovation': LucideIcons.hardHat,
      'daycare': LucideIcons.baby,
      'school_bus': LucideIcons.bus,
      'tutor': LucideIcons.bookOpenCheck,
      'cleaning': LucideIcons.sparkles,
      'laundry': LucideIcons.washingMachine,
      'repair': LucideIcons.wrench,
    },
    'Travel & Places': {
      'passport': LucideIcons.bookKey,
      'visa': LucideIcons.stamp,
      'luggage': LucideIcons.luggage,
      'backpack': LucideIcons.backpack,
      'camping': LucideIcons.tent,
      'hiking': LucideIcons.mountain,
      'skiing': LucideIcons.snowflake,
      'cruise': LucideIcons.sailboat,
      'road_trip': LucideIcons.route,
      'monument': LucideIcons.landmark,
      'temple': LucideIcons.landmark,
      'airport': LucideIcons.planeTakeoff,
      'railway': LucideIcons.trainTrack,
      'toll_booth': LucideIcons.milestone,
      'maps': LucideIcons.mapPinned,
      'compass': LucideIcons.compass,
      'hotel': LucideIcons.bed,
    },
    'Social & Giving': {
      'wedding': LucideIcons.heart,
      'birthday': LucideIcons.cake,
      'baby_shower': LucideIcons.baby,
      'housewarming': LucideIcons.housePlus,
      'farewell': LucideIcons.hand,
      'tip': LucideIcons.coins,
      'crowdfunding': LucideIcons.users,
      'volunteer': LucideIcons.handHelping,
      'ngo': LucideIcons.ribbon,
      'tithe': LucideIcons.church,
      'gift': LucideIcons.gift,
      'donation': LucideIcons.handHeart,
    },
    'Work & Business': {
      'business': LucideIcons.building2,
      'work': LucideIcons.briefcaseBusiness,
      'computer': LucideIcons.laptop,
      'phone': LucideIcons.phone,
      'meeting': LucideIcons.usersRound,
      'presentation': LucideIcons.presentation,
      'conference': LucideIcons.projector,
      'networking': LucideIcons.network,
      'coworking': LucideIcons.building,
      'freelance': LucideIcons.laptopMinimal,
      'startup': LucideIcons.rocket,
      'patent': LucideIcons.scrollText,
      'trademark': LucideIcons.copyright,
      'uniform': LucideIcons.shirt,
      'id_card': LucideIcons.idCard,
      'parking_office': LucideIcons.squareParking,
      'freelance_income': LucideIcons.laptopMinimal,
      'commission': LucideIcons.handshake,
      'lend': LucideIcons.arrowUpRight,
      'borrow': LucideIcons.arrowDownLeft,
      'tools': LucideIcons.hammer,
    },
    'Misc': {
      'smoking': LucideIcons.cigarette,
      'alcohol': LucideIcons.beer,
      'lottery': LucideIcons.dices,
      'astrology': LucideIcons.moon,
      'newspaper': LucideIcons.newspaper,
      'magazine': LucideIcons.bookOpenText,
      'stationery': LucideIcons.pencil,
      'umbrella': LucideIcons.umbrella,
      'sunglasses': LucideIcons.glasses,
      'clock': LucideIcons.clock,
      'timer': LucideIcons.timer,
      'calendar': LucideIcons.calendar,
      'calendar_event': LucideIcons.calendarDays,
      'bell': LucideIcons.bell,
      'notification': LucideIcons.bellRing,
      'alert': LucideIcons.triangleAlert,
      'star': LucideIcons.star,
      'heart': LucideIcons.heart,
      'flag': LucideIcons.flag,
      'bookmark': LucideIcons.bookmark,
      'pin': LucideIcons.pin,
      'sort': LucideIcons.arrowUpDown,
      'share': LucideIcons.share2,
      'export': LucideIcons.fileOutput,
      'import': LucideIcons.fileInput,
      'settings': LucideIcons.settings,
      'search': LucideIcons.search,
      'filter': LucideIcons.listFilter,
      'info': LucideIcons.info,
      'help': LucideIcons.circleQuestionMark,
      'lock': LucideIcons.lock,
      'category': LucideIcons.tag,
      'pie_chart': LucideIcons.chartPie,
      'others': LucideIcons.ellipsis,
      'grid': LucideIcons.layoutGrid,
      'briefcase': LucideIcons.briefcase,
      'map': LucideIcons.map,
      'pets': LucideIcons.pawPrint,
      'repeat': LucideIcons.repeat,
      'photo': LucideIcons.image,
    },
  };

  /// Flat map derived from iconGroups — single source of truth
  static final Map<String, IconData> iconMap = {
    for (final group in iconGroups.values) ...group,
  };

  static IconData getIconData(String? iconName) {
    if (iconName == null || iconName.isEmpty) {
      return LucideIcons.circleQuestionMark;
    }
    final icon = iconMap[iconName];
    if (icon == null) {
      debugPrint('⚠️ IconHelper: missing icon "$iconName"');
      return LucideIcons.circleQuestionMark;
    }
    return icon;
  }

  static List<String> getAllIconNames() => iconMap.keys.toList();
}
