import 'package:flutter/material.dart';
import 'package:lucide_icons_flutter/lucide_icons.dart';

class IconHelper {
  static IconData iconFromName(String name) {
    return iconMap[name] ?? LucideIcons.circleQuestionMark;
  }

  static final Map<String, IconData> iconMap = {
    'category': LucideIcons.tag,
    'pie_chart': LucideIcons.chartPie,
    'receipt_long': LucideIcons.receipt,
    'repeat': LucideIcons.repeat,
    'card_travel': LucideIcons.creditCard,
    'sms': LucideIcons.messageSquare,
    'backup': LucideIcons.download,
    'auto_graph': LucideIcons.trendingUp,
    'lock': LucideIcons.lock,
    'home': LucideIcons.house,
    'shopping_cart': LucideIcons.shoppingCart,
    'fastfood': LucideIcons.utensils,
    'restaurant': LucideIcons.utensils,
    'coffee': LucideIcons.coffee,
    'flight': LucideIcons.plane,
    'directions_car': LucideIcons.car,
    'local_hospital': LucideIcons.heart,
    'savings': LucideIcons.piggyBank,
    'attach_money': LucideIcons.dollarSign,
    'credit_card': LucideIcons.creditCard,
    'wallet': LucideIcons.wallet,
    'account_balance_wallet': LucideIcons.wallet,
    'subscriptions': LucideIcons.repeat,
    'school': LucideIcons.graduationCap,
    'pets': LucideIcons.heart,
    'gift': LucideIcons.gift,
    'travel': LucideIcons.mapPin,
    'entertainment': LucideIcons.film,
    'movie': LucideIcons.film,
    'groceries': LucideIcons.shoppingBag,
    'clothing': LucideIcons.shirt,
    'checkroom': LucideIcons.shirt,
    'bills': LucideIcons.receipt,
    'receipt': LucideIcons.receipt,
    'trending_up': LucideIcons.trendingUp,
    'shopping_bag': LucideIcons.shoppingBag,
    'fitness': LucideIcons.dumbbell,
    'sports': LucideIcons.trophy,
    'work': LucideIcons.briefcase,
    'business': LucideIcons.building,
    'phone': LucideIcons.phone,
    'wifi': LucideIcons.wifi,
    'electric': LucideIcons.zap,
    'bolt': LucideIcons.zap,
    'water': LucideIcons.droplets,
    'gas': LucideIcons.fuel,
    'local_gas_station': LucideIcons.fuel,
    'medical': LucideIcons.stethoscope,
    'pharmacy': LucideIcons.pill,
    'beauty': LucideIcons.sparkles,
    'spa': LucideIcons.sparkles,
    'hotel': LucideIcons.bed,
    'beach': LucideIcons.treePalm,
    'park': LucideIcons.trees,
    'music': LucideIcons.music,
    'games': LucideIcons.gamepad2,
    'book': LucideIcons.book,
    'library': LucideIcons.bookOpen,
    'art': LucideIcons.palette,
    'camera': LucideIcons.camera,
    'photo': LucideIcons.image,
    'celebration': LucideIcons.partyPopper,
    'cake': LucideIcons.cake,
    'wine': LucideIcons.wine,
    'nightlife': LucideIcons.music,
    'child': LucideIcons.baby,
    'baby': LucideIcons.baby,
    'toys': LucideIcons.gamepad2,
    'cleaning': LucideIcons.sprayCan,
    'laundry': LucideIcons.shirt,
    'repair': LucideIcons.wrench,
    'tools': LucideIcons.hammer,
    'garden': LucideIcons.flower,
    'furniture': LucideIcons.armchair,
    'electronics': LucideIcons.smartphone,
    'devices': LucideIcons.smartphone,
    'computer': LucideIcons.laptop,
    'phone_mobile': LucideIcons.smartphone,
    'watch': LucideIcons.watch,
    'headphones': LucideIcons.headphones,
    'tv': LucideIcons.tv,
    'videogame': LucideIcons.gamepad2,
    'print': LucideIcons.printer,
    'mail': LucideIcons.mail,
    'delivery': LucideIcons.truck,
    'taxi': LucideIcons.car,
    'bus': LucideIcons.bus,
    'directions_bus': LucideIcons.bus,
    'train': LucideIcons.trainFront,
    'subway': LucideIcons.trainFrontTunnel,
    'bike': LucideIcons.bike,
    'walk': LucideIcons.footprints,
    'parking': LucideIcons.circleParking,
    'atm': LucideIcons.banknote,
    'bank': LucideIcons.landmark,
    'insurance': LucideIcons.shield,
    'investment': LucideIcons.trendingUp,
    'tax': LucideIcons.receipt,
    'salary': LucideIcons.banknote,
    'bonus': LucideIcons.gift,
    'refund': LucideIcons.rotateCcw,
    'donation': LucideIcons.heart,
    'charity': LucideIcons.heart,
    'others': LucideIcons.ellipsis,
  };

  /// Maps icon names (stored as strings) to actual IconData
  static IconData getIconData(String? iconName) {
    return iconMap[iconName] ?? Icons.category; // Fallback to a default
  }

  /// Get a list of all supported icon names
  static List<String> getAllIconNames() => iconMap.keys.toList();
}
