import 'package:flutter/services.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:intl/intl.dart';
import '../export_plugin.dart';

class StandardPdfExportPlugin extends ExportPlugin {
  @override
  String get id => 'standard_pdf_export';

  @override
  String get name => 'Standard PDF Export';

  @override
  String get version => '1.0.0';

  @override
  String get exportType => 'PDF';

  @override
  String get templateName => 'Standard';

  @override
  bool supportsTemplate(String templateType) => templateType == 'standard';

  @override
  Future<Uint8List> generateExport(ExportData data) async {
    final pdf = pw.Document();
    final font = await _loadFont();
    final now = DateTime.now();

    pdf.addPage(
      pw.MultiPage(
        theme: font,
        pageFormat: PdfPageFormat.a4,
        build: (context) => [
          _buildHeader(data, now),
          pw.SizedBox(height: 10),
          _buildReportInfo(data, now),
          pw.SizedBox(height: 20),
          _buildSummary(data),
          pw.SizedBox(height: 20),
          _buildCategoryTable(data),
          pw.SizedBox(height: 20),
          _buildTransactionTable(data),
        ],
        footer: (context) => _buildFooter(context, now),
      ),
    );

    return pdf.save();
  }

  Future<pw.ThemeData> _loadFont() async {
    final font =
        pw.Font.ttf(await rootBundle.load('assets/fonts/Inter-Variable.ttf'));
    final fallback = pw.Font.ttf(
      await rootBundle
          .load('assets/fonts/NotoSansDevanagari-Variable.ttf'),
    );
    final bengaliFallback = pw.Font.ttf(
      await rootBundle.load('assets/fonts/NotoSansBengali-Variable.ttf'),
    );
    return pw.ThemeData.withFont(base: font, fontFallback: [fallback, bengaliFallback]);
  }

  pw.Widget _buildHeader(ExportData data, DateTime now) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(16),
      decoration: const pw.BoxDecoration(
        color: PdfColors.blue900,
        borderRadius: pw.BorderRadius.all(pw.Radius.circular(8)),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            'MUDRA MANAGER',
            style: pw.TextStyle(
              fontSize: 24,
              fontWeight: pw.FontWeight.bold,
              color: PdfColors.white,
            ),
          ),
          pw.Text(
            'Financial Report',
            style: const pw.TextStyle(fontSize: 16, color: PdfColors.white),
          ),
        ],
      ),
    );
  }

  pw.Widget _buildReportInfo(ExportData data, DateTime now) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(12),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey300),
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          _buildInfoRow('Generated By:', data.userName ?? 'User'),
          pw.SizedBox(height: 4),
          _buildInfoRow(
            'Generated On:',
            DateFormat('dd MMM yyyy, hh:mm a').format(now),
          ),
          pw.SizedBox(height: 4),
          _buildInfoRow(
            'Report Period:',
            '${DateFormat('dd MMM yyyy').format(data.startDate)} - ${DateFormat('dd MMM yyyy').format(data.endDate)}',
          ),
        ],
      ),
    );
  }

  pw.Widget _buildInfoRow(String label, String value) {
    return pw.Row(
      children: [
        pw.SizedBox(
          width: 120,
          child: pw.Text(
            label,
            style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10),
          ),
        ),
        pw.Text(value, style: const pw.TextStyle(fontSize: 10)),
      ],
    );
  }

  pw.Widget _buildSummary(ExportData data) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          'Financial Summary',
          style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold),
        ),
        pw.SizedBox(height: 10),
        pw.Container(
          padding: const pw.EdgeInsets.all(16),
          decoration: const pw.BoxDecoration(
            color: PdfColors.grey100,
            borderRadius: pw.BorderRadius.all(pw.Radius.circular(8)),
          ),
          child: pw.Column(
            children: [
              _buildSummaryRow(
                'Total Income',
                '${data.currency}${data.income.toStringAsFixed(2)}',
                PdfColors.green,
              ),
              pw.SizedBox(height: 8),
              _buildSummaryRow(
                'Total Expense',
                '${data.currency}${data.expense.toStringAsFixed(2)}',
                PdfColors.red,
              ),
              pw.SizedBox(height: 8),
              pw.Divider(),
              pw.SizedBox(height: 8),
              _buildSummaryRow(
                'Net Savings',
                '${data.currency}${(data.income - data.expense).toStringAsFixed(2)}',
                PdfColors.blue900,
                bold: true,
              ),
              pw.SizedBox(height: 8),
              _buildSummaryRow(
                'Savings Rate',
                '${data.savingsRate.toStringAsFixed(1)}%',
                PdfColors.blue900,
              ),
              pw.SizedBox(height: 8),
              _buildSummaryRow(
                'Avg Daily Spend',
                '${data.currency}${data.avgDailySpend.toStringAsFixed(2)}',
                PdfColors.grey800,
              ),
            ],
          ),
        ),
      ],
    );
  }

  pw.Widget _buildSummaryRow(
    String label,
    String value,
    PdfColor color, {
    bool bold = false,
  }) {
    return pw.Row(
      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
      children: [
        pw.Text(label, style: const pw.TextStyle(fontSize: 12)),
        pw.Text(
          value,
          style: pw.TextStyle(
            fontWeight: bold ? pw.FontWeight.bold : pw.FontWeight.normal,
            fontSize: bold ? 14 : 12,
            color: color,
          ),
        ),
      ],
    );
  }

  pw.Widget _buildCategoryTable(ExportData data) {
    final total = data.categoryData.values.fold(0.0, (sum, val) => sum + val);
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          'Category Breakdown',
          style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold),
        ),
        pw.SizedBox(height: 10),
        pw.TableHelper.fromTextArray(
          headerStyle: pw.TextStyle(
            fontWeight: pw.FontWeight.bold,
            color: PdfColors.white,
          ),
          headerDecoration: const pw.BoxDecoration(color: PdfColors.blue900),
          cellAlignment: pw.Alignment.centerLeft,
          headers: ['Category', 'Amount', 'Percentage'],
          data: data.categoryData.entries.map((entry) {
            final percentage = total > 0 ? (entry.value / total * 100) : 0.0;
            return [
              data.categoryDataMap[entry.key]?.name ?? 'Unknown',
              '${data.currency}${entry.value.toStringAsFixed(2)}',
              '${percentage.toStringAsFixed(1)}%',
            ];
          }).toList(),
        ),
      ],
    );
  }

  pw.Widget _buildTransactionTable(ExportData data) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          'Recent Transactions',
          style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold),
        ),
        pw.SizedBox(height: 10),
        pw.TableHelper.fromTextArray(
          headerStyle: pw.TextStyle(
            fontWeight: pw.FontWeight.bold,
            color: PdfColors.white,
          ),
          headerDecoration: const pw.BoxDecoration(color: PdfColors.blue900),
          cellAlignment: pw.Alignment.centerLeft,
          headers: ['Date', 'Category', 'Amount', 'Currency', 'Base Amt', 'Type'],
          data: data.transactions
              .take(20)
              .map(
                (txn) => [
                  DateFormat('dd/MM/yyyy').format(txn.date),
                  txn.category.value?.name ?? 'Unknown',
                  txn.amount.toStringAsFixed(2),
                  txn.currencyCode ?? data.currency,
                  '${data.currency}${txn.baseAmount.toStringAsFixed(2)}',
                  txn.isExpense ? 'Expense' : 'Income',
                ],
              )
              .toList(),
        ),
      ],
    );
  }

  pw.Widget _buildFooter(pw.Context context, DateTime now) {
    return pw.Container(
      margin: const pw.EdgeInsets.only(top: 10),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(
            'Made with Mudra Manager • mudramanager.com',
            style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey),
          ),
          pw.Text(
            'Page ${context.pageNumber} of ${context.pagesCount}',
            style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey),
          ),
        ],
      ),
    );
  }

  @override
  void onLoad() {}

  @override
  void onStart() {}
}
