import 'package:flutter/foundation.dart';
import 'package:excel/excel.dart';
import 'package:intl/intl.dart';
import '../export_plugin.dart';

class StandardExcelExportPlugin extends ExportPlugin {
  @override
  String get id => 'standard_excel_export';

  @override
  String get name => 'Standard Excel Export';

  @override
  String get version => '1.0.0';

  @override
  String get exportType => 'Excel';

  @override
  String get templateName => 'Standard';

  @override
  bool supportsTemplate(String templateType) => templateType == 'standard';

  @override
  Future<Uint8List> generateExport(ExportData data) async {
    final excel = Excel.createExcel();
    excel.delete('Sheet1');

    _createSummarySheet(excel, data);
    _createCategorySheet(excel, data);
    _createTransactionSheet(excel, data);

    final bytes = excel.encode();
    return Uint8List.fromList(bytes!);
  }

  void _createSummarySheet(Excel excel, ExportData data) {
    final summary = excel['Summary'];
    final now = DateTime.now();
    
    // Header
    summary.cell(CellIndex.indexByString('A1')).value = TextCellValue('MUDRA MANAGER - FINANCIAL REPORT');
    summary.cell(CellIndex.indexByString('A1')).cellStyle = CellStyle(bold: true, fontSize: 16);
    
    // Report Info
    summary.cell(CellIndex.indexByString('A3')).value = TextCellValue('Generated By:');
    summary.cell(CellIndex.indexByString('B3')).value = TextCellValue(data.userName ?? 'User');
    summary.cell(CellIndex.indexByString('A4')).value = TextCellValue('Generated On:');
    summary.cell(CellIndex.indexByString('B4')).value = TextCellValue(DateFormat('dd MMM yyyy, hh:mm a').format(now));
    summary.cell(CellIndex.indexByString('A5')).value = TextCellValue('Report Period:');
    summary.cell(CellIndex.indexByString('B5')).value = TextCellValue('${DateFormat('dd MMM yyyy').format(data.startDate)} - ${DateFormat('dd MMM yyyy').format(data.endDate)}');
    
    // Financial Summary
    summary.cell(CellIndex.indexByString('A7')).value = TextCellValue('FINANCIAL SUMMARY');
    summary.cell(CellIndex.indexByString('A7')).cellStyle = CellStyle(bold: true, fontSize: 14);
    
    summary.cell(CellIndex.indexByString('A9')).value = TextCellValue('Total Income');
    summary.cell(CellIndex.indexByString('B9')).value = TextCellValue('${data.currency}${data.income.toStringAsFixed(2)}');
    summary.cell(CellIndex.indexByString('A10')).value = TextCellValue('Total Expense');
    summary.cell(CellIndex.indexByString('B10')).value = TextCellValue('${data.currency}${data.expense.toStringAsFixed(2)}');
    summary.cell(CellIndex.indexByString('A11')).value = TextCellValue('Net Savings');
    summary.cell(CellIndex.indexByString('B11')).value = TextCellValue('${data.currency}${(data.income - data.expense).toStringAsFixed(2)}');
    summary.cell(CellIndex.indexByString('B11')).cellStyle = CellStyle(bold: true);
    summary.cell(CellIndex.indexByString('A12')).value = TextCellValue('Savings Rate');
    summary.cell(CellIndex.indexByString('B12')).value = TextCellValue('${data.savingsRate.toStringAsFixed(1)}%');
    summary.cell(CellIndex.indexByString('A13')).value = TextCellValue('Avg Daily Spend');
    summary.cell(CellIndex.indexByString('B13')).value = TextCellValue('${data.currency}${data.avgDailySpend.toStringAsFixed(2)}');
  }

  void _createCategorySheet(Excel excel, ExportData data) {
    final categorySheet = excel['Categories'];
    
    categorySheet.cell(CellIndex.indexByString('A1')).value = TextCellValue('CATEGORY BREAKDOWN');
    categorySheet.cell(CellIndex.indexByString('A1')).cellStyle = CellStyle(bold: true, fontSize: 14);
    
    categorySheet.cell(CellIndex.indexByString('A3')).value = TextCellValue('Category');
    categorySheet.cell(CellIndex.indexByString('B3')).value = TextCellValue('Amount');
    categorySheet.cell(CellIndex.indexByString('C3')).value = TextCellValue('Percentage');
    categorySheet.cell(CellIndex.indexByString('A3')).cellStyle = CellStyle(bold: true);
    categorySheet.cell(CellIndex.indexByString('B3')).cellStyle = CellStyle(bold: true);
    categorySheet.cell(CellIndex.indexByString('C3')).cellStyle = CellStyle(bold: true);

    final total = data.categoryData.values.fold(0.0, (sum, val) => sum + val);
    int row = 4;
    for (var entry in data.categoryData.entries) {
      final percentage = total > 0 ? (entry.value / total * 100) : 0.0;
      categorySheet.cell(CellIndex.indexByString('A$row')).value = TextCellValue(data.categoryDataMap[entry.key]?.name ?? 'Unknown');
      categorySheet.cell(CellIndex.indexByString('B$row')).value = TextCellValue('${data.currency}${entry.value.toStringAsFixed(2)}');
      categorySheet.cell(CellIndex.indexByString('C$row')).value = TextCellValue('${percentage.toStringAsFixed(1)}%');
      row++;
    }
  }

  void _createTransactionSheet(Excel excel, ExportData data) {
    final txnSheet = excel['Transactions'];
    
    txnSheet.cell(CellIndex.indexByString('A1')).value = TextCellValue('TRANSACTION HISTORY');
    txnSheet.cell(CellIndex.indexByString('A1')).cellStyle = CellStyle(bold: true, fontSize: 14);
    
    txnSheet.cell(CellIndex.indexByString('A3')).value = TextCellValue('Date');
    txnSheet.cell(CellIndex.indexByString('B3')).value = TextCellValue('Category');
    txnSheet.cell(CellIndex.indexByString('C3')).value = TextCellValue('Amount');
    txnSheet.cell(CellIndex.indexByString('D3')).value = TextCellValue('Currency');
    txnSheet.cell(CellIndex.indexByString('E3')).value = TextCellValue('Base Amount');
    txnSheet.cell(CellIndex.indexByString('F3')).value = TextCellValue('Type');
    txnSheet.cell(CellIndex.indexByString('A3')).cellStyle = CellStyle(bold: true);
    txnSheet.cell(CellIndex.indexByString('B3')).cellStyle = CellStyle(bold: true);
    txnSheet.cell(CellIndex.indexByString('C3')).cellStyle = CellStyle(bold: true);
    txnSheet.cell(CellIndex.indexByString('D3')).cellStyle = CellStyle(bold: true);
    txnSheet.cell(CellIndex.indexByString('E3')).cellStyle = CellStyle(bold: true);
    txnSheet.cell(CellIndex.indexByString('F3')).cellStyle = CellStyle(bold: true);

    int row = 4;
    for (var txn in data.transactions) {
      final txnCurrency = txn.currencyCode;
      txnSheet.cell(CellIndex.indexByString('A$row')).value = TextCellValue(DateFormat('dd/MM/yyyy').format(txn.date));
      txnSheet.cell(CellIndex.indexByString('B$row')).value = TextCellValue(txn.category.value?.name ?? 'Unknown');
      txnSheet.cell(CellIndex.indexByString('C$row')).value = TextCellValue('${txn.amount.toStringAsFixed(2)}');
      txnSheet.cell(CellIndex.indexByString('D$row')).value = TextCellValue(txnCurrency ?? data.currency);
      txnSheet.cell(CellIndex.indexByString('E$row')).value = TextCellValue('${data.currency}${txn.baseAmount.toStringAsFixed(2)}');
      txnSheet.cell(CellIndex.indexByString('F$row')).value = TextCellValue(txn.isExpense ? 'Expense' : 'Income');
      row++;
    }
  }

  @override
  void onLoad() {}

  @override
  void onStart() {}
}
