import 'package:flutter/foundation.dart';
import 'package:excel/excel.dart';
import 'package:intl/intl.dart';
import '../export_plugin.dart';

class StandardExcelExportPlugin extends ExportPlugin {
  @override
  String get id => 'standard_excel_export';

  @override
  String get name => 'Standard Excel Export';

  @override
  String get version => '1.0.0';

  @override
  String get exportType => 'Excel';

  @override
  String get templateName => 'Standard';

  @override
  bool supportsTemplate(String templateType) => templateType == 'standard';

  @override
  Future<Uint8List> generateExport(ExportData data) async {
    final excel = Excel.createExcel();
    excel.delete('Sheet1');

    _createSummarySheet(excel, data);
    _createCategorySheet(excel, data);
    _createTransactionSheet(excel, data);

    final bytes = excel.encode();
    return Uint8List.fromList(bytes!);
  }

  void _createSummarySheet(Excel excel, ExportData data) {
    final summary = excel['Summary'];
    final now = DateTime.now();
    
    // Header
    summary.cell(CellIndex.indexByString('A1')).value = 'MUDRA MANAGER - FINANCIAL REPORT';
    summary.cell(CellIndex.indexByString('A1')).cellStyle = CellStyle(bold: true, fontSize: 16);
    
    // Report Info
    summary.cell(CellIndex.indexByString('A3')).value = 'Generated By:';
    summary.cell(CellIndex.indexByString('B3')).value = data.userName ?? 'User';
    summary.cell(CellIndex.indexByString('A4')).value = 'Generated On:';
    summary.cell(CellIndex.indexByString('B4')).value = DateFormat('dd MMM yyyy, hh:mm a').format(now);
    summary.cell(CellIndex.indexByString('A5')).value = 'Report Period:';
    summary.cell(CellIndex.indexByString('B5')).value = '${DateFormat('dd MMM yyyy').format(data.startDate)} - ${DateFormat('dd MMM yyyy').format(data.endDate)}';
    
    // Financial Summary
    summary.cell(CellIndex.indexByString('A7')).value = 'FINANCIAL SUMMARY';
    summary.cell(CellIndex.indexByString('A7')).cellStyle = CellStyle(bold: true, fontSize: 14);
    
    summary.cell(CellIndex.indexByString('A9')).value = 'Total Income';
    summary.cell(CellIndex.indexByString('B9')).value = '${data.currency}${data.income.toStringAsFixed(2)}';
    summary.cell(CellIndex.indexByString('A10')).value = 'Total Expense';
    summary.cell(CellIndex.indexByString('B10')).value = '${data.currency}${data.expense.toStringAsFixed(2)}';
    summary.cell(CellIndex.indexByString('A11')).value = 'Net Savings';
    summary.cell(CellIndex.indexByString('B11')).value = '${data.currency}${(data.income - data.expense).toStringAsFixed(2)}';
    summary.cell(CellIndex.indexByString('B11')).cellStyle = CellStyle(bold: true);
    summary.cell(CellIndex.indexByString('A12')).value = 'Savings Rate';
    summary.cell(CellIndex.indexByString('B12')).value = '${data.savingsRate.toStringAsFixed(1)}%';
    summary.cell(CellIndex.indexByString('A13')).value = 'Avg Daily Spend';
    summary.cell(CellIndex.indexByString('B13')).value = '${data.currency}${data.avgDailySpend.toStringAsFixed(2)}';
  }

  void _createCategorySheet(Excel excel, ExportData data) {
    final categorySheet = excel['Categories'];
    
    categorySheet.cell(CellIndex.indexByString('A1')).value = 'CATEGORY BREAKDOWN';
    categorySheet.cell(CellIndex.indexByString('A1')).cellStyle = CellStyle(bold: true, fontSize: 14);
    
    categorySheet.cell(CellIndex.indexByString('A3')).value = 'Category';
    categorySheet.cell(CellIndex.indexByString('B3')).value = 'Amount';
    categorySheet.cell(CellIndex.indexByString('C3')).value = 'Percentage';
    categorySheet.cell(CellIndex.indexByString('A3')).cellStyle = CellStyle(bold: true);
    categorySheet.cell(CellIndex.indexByString('B3')).cellStyle = CellStyle(bold: true);
    categorySheet.cell(CellIndex.indexByString('C3')).cellStyle = CellStyle(bold: true);

    final total = data.categoryData.values.fold(0.0, (sum, val) => sum + val);
    int row = 4;
    for (var entry in data.categoryData.entries) {
      final percentage = total > 0 ? (entry.value / total * 100) : 0.0;
      categorySheet.cell(CellIndex.indexByString('A$row')).value = data.categoryDataMap[entry.key]?.name ?? 'Unknown';
      categorySheet.cell(CellIndex.indexByString('B$row')).value = '${data.currency}${entry.value.toStringAsFixed(2)}';
      categorySheet.cell(CellIndex.indexByString('C$row')).value = '${percentage.toStringAsFixed(1)}%';
      row++;
    }
  }

  void _createTransactionSheet(Excel excel, ExportData data) {
    final txnSheet = excel['Transactions'];
    
    txnSheet.cell(CellIndex.indexByString('A1')).value = 'TRANSACTION HISTORY';
    txnSheet.cell(CellIndex.indexByString('A1')).cellStyle = CellStyle(bold: true, fontSize: 14);
    
    txnSheet.cell(CellIndex.indexByString('A3')).value = 'Date';
    txnSheet.cell(CellIndex.indexByString('B3')).value = 'Category';
    txnSheet.cell(CellIndex.indexByString('C3')).value = 'Amount';
    txnSheet.cell(CellIndex.indexByString('D3')).value = 'Currency';
    txnSheet.cell(CellIndex.indexByString('E3')).value = 'Base Amount';
    txnSheet.cell(CellIndex.indexByString('F3')).value = 'Type';
    txnSheet.cell(CellIndex.indexByString('A3')).cellStyle = CellStyle(bold: true);
    txnSheet.cell(CellIndex.indexByString('B3')).cellStyle = CellStyle(bold: true);
    txnSheet.cell(CellIndex.indexByString('C3')).cellStyle = CellStyle(bold: true);
    txnSheet.cell(CellIndex.indexByString('D3')).cellStyle = CellStyle(bold: true);
    txnSheet.cell(CellIndex.indexByString('E3')).cellStyle = CellStyle(bold: true);
    txnSheet.cell(CellIndex.indexByString('F3')).cellStyle = CellStyle(bold: true);

    int row = 4;
    for (var txn in data.transactions) {
      final txnCurrency = txn.currencyCode;
      txnSheet.cell(CellIndex.indexByString('A$row')).value = DateFormat('dd/MM/yyyy').format(txn.date);
      txnSheet.cell(CellIndex.indexByString('B$row')).value = txn.category.value?.name ?? 'Unknown';
      txnSheet.cell(CellIndex.indexByString('C$row')).value = '${txn.amount.toStringAsFixed(2)}';
      txnSheet.cell(CellIndex.indexByString('D$row')).value = txnCurrency ?? data.currency;
      txnSheet.cell(CellIndex.indexByString('E$row')).value = '${data.currency}${txn.baseAmount.toStringAsFixed(2)}';
      txnSheet.cell(CellIndex.indexByString('F$row')).value = txn.isExpense ? 'Expense' : 'Income';
      row++;
    }
  }

  @override
  void onLoad() {}

  @override
  void onStart() {}
}
